version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/pleaseletmein
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "neo4j-admin", "check", "--database=neo4j"]
      interval: 10s
      timeout: 30s
      retries: 3

  api:
    build:
      context: ./server
    container_name: api
    environment:
      - NODE_ENV=development
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=pleaseletmein
    ports:
      - "5000:5000"
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
  
  client:
    build:
      context: ./client
    container_name: client
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  neo4j_data:
  neo4j_logs: